---
baseURL: "/"
languageCode: "en-us"
title: "Kustomize WWW"
theme: "replicated-docs-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Landing Page for Kustomize"
googleAnalytics: "UA-61084834-1"

Params:
  author: "Replicated"
  copyright: "Replicated, Inc"
  search_env: "staging"

  favicon: ""
  pagetitle: "Replicated"
  permalink: "#"

  docker_version_default: "17.06.2-ce"
  docker_version_minimum: "1.7.1"
  replicated_api_version_current: "2.20.2"
  replicated_latest_version: "2.20.2"
  replicated_latest_release_date: "April 26, 2018"

  swarm_docker_version_minimum: "1.13.1"
  swarm_docker_version_default: "17.06.2-ce"

  kubernetes_docker_version_minimum: "1.12.3"
  kubernetes_docker_version_default: "1.12.3"
  kubernetes_version: "1.9.3"

taxonomies:
  category: "categories"
  tag: "tags"
  kb-section: "kb-sections"

algolia:
  index: "ship_staging"
  appID: "5PHVQPX4AR"

menu:
  main:
    - Name: "Docs"
      Weight: 1
      URL: "https://github.com/kubernetes-sigs/kustomize/blob/master/docs/workflows.md"
    - Name: "Overview"
      Weight: 2
      URL: "#overview"
    - Name: "Resources"
      Weight: 3
      URL: "#resources"
    - Name: "Community"
      Weight: 4
      URL: "#community"
---
