---
baseURL: "/"
languageCode: "en-us"
title: "Kustomize WWW"
theme: "replicated-docs-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Landing Page for Kustomize"
googleAnalytics: "UA-61420213-8"

Params:
  author: "Replicated"
  copyright: "Replicated, Inc"
  search_env: "prod"

  matomo:
    host: "data-2.replicated.com"
    site: "5"

  favicon: ""
  pagetitle: "Kustomize"
  permalink: "#"

taxonomies:
  category: "categories"
  tag: "tags"
  kb-section: "kb-sections"

menu:
  main:
    - Name: "apply -k Docs"
      Weight: 1
      URL: "https://kubectl.docs.kubernetes.io/pages/app_management/introduction.html"
    - Name: "binary Docs"
      Weight: 2
      URL: "https://github.com/kubernetes-sigs/kustomize/blob/master/docs"
    - Name: "Overview"
      Weight: 3
      URL: "#overview"
    - Name: "Resources"
      Weight: 4
      URL: "#resources"
    - Name: "Community"
      Weight: 5
      URL: "#community"
---
